openapi: 3.1.0
info:
  title: STD24161
  description: This is a specification of STD24161
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:8000'
paths:
  /cars:
    get:
      requestBody:
        description: This is a specification of STD24161
        content:
          'application/json':
            schema:
              type: string
              $ref: '#/components/schemas/Cars'



